apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: le-staging
  namespace: whoami
spec:
  acme:
    email: ryan_harbert@wgbh.org
    # We use the staging server here for testing to avoid hitting
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # if not existing, it will register a new account and stores it
      name: wgbh-mla
    solvers:
      - http01:
          # The ingressClass used to create the necessary ingress routes
          ingress:
            class: traefik
