apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openvault.backend.fullname" . }}-secret
  labels:
{{ include "bjw-s.common.lib.metadata.allLabels" . | indent 4 }}
stringData:
  # Auth configuration
  AUTH0_CLIENT_ID: {{ .Values.auth.clientId | default "" | quote }}
  AUTH0_CLIENT_SECRET: {{ .Values.auth.clientSecret | default "" | quote }}
  AUTH0_URL: {{ .Values.auth.url | default "" | quote }}

  # AWS configuration
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | default "" | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | default "" | quote }}

  # Elasticsearch configuration
  ES_USERNAME: {{ .Values.elasticsearch.username | default "" | quote }}
  ES_PASSWORD: {{ .Values.elasticsearch.password | default "" | quote }}

  # Google configuration
  GOOGLE_CLIENT_ID: {{ .Values.google.clientId | default "" | quote }}

  # OpenVault configuration
  OV_DB_HOST: {{ .Values.db.host | default "postgres.postgres" | quote }}
  OV_DB_NAME: {{ .Values.db.name | default .Release.Name | quote }}
  OV_DB_PASSWORD: {{ .Values.db.password | default "" | quote }}
  OV_DB_PORT: {{ .Values.db.port | default "5432" | quote }}
  OV_DB_USER: {{ .Values.db.user | default "postgres" | quote }}
  OV_SECRET_KEY: {{ randAlphaNum 32 | quote }}
