changelog:
  categories:
    - title: Breaking Changes 🪅
      labels:
        - breaking 💔

    - title: New Features 🎉
      labels:
        - enhancement ➕

    - title: Bugfixes 🐛
      labels:
        - bug 🐛

    - title: Deployment 🚀
      labels:
        - production 🎭
        - dev 💻

    - title: Maintenance 🔩
      labels:
        - maintenance 🔧
        - CI 🦾
        - CD 🏗️

    - title: Documentation 📚
      labels:
        - documentation 📜

    - title: Other Changes
      labels:
        - '*'
