#!/usr/bin/env python3
###
# Command line tool for managing Open Vault database
###
from ast import alias
from deployer import KubeContext, run
import click


def get_pod_name(workload: str):
    return run(
        f'kubectl get pods -l workload.user.cattle.io/workloadselector="deployment-openvault-{ workload }" -o name'
    ).split('\n')[0]


@click.group()
@click.option(
    '--context',
    '-c',
    required=True,
    help='the kubectl context to use',
    type=click.Choice(['openvault', 'openvault-demo']),
)
def cli(context: str, **kwargs):
    # db = KubeContext(**kwargs)
    run(f'kubectl config use-context { context }')
    click.echo(f'context set to { context }')


@cli.command()
def backup():
    click.echo('backing up!')
    pod = get_pod_name('db')
    run(
        f'kubectl exec -it { pod } -- /usr/local/bin/pg_dump -Fc -U postgres postgres > db_$(date +%Y-%m-%d_%H-%M-%S).sql'
    )


@cli.command()
@click.argument(
    'filename',
    required=True,
    type=click.File('rb'),
)
def restore(filename: str):
    click.echo(f'restoring database to { filename }')
    pod = get_pod_name('db')
    run(
        f'kubectl exec -it { pod } -- /usr/local/bin/pg_restore --verbose --clean --no-acl --no-owner -U postgres -d postgres < { filename }'
    )


if __name__ == '__main__':
    cli()
