#!/usr/bin/env python3
###
# Command line tool for managing Open Vault deployments
###
from deployer import Deployer


if __name__ == '__main__':
    from cli import cli

    args = cli()

    # Create a new Deployer instance form parsed command line args.
    deployer = Deployer(**vars(args))

    # Run the deployment.
    deployer.deploy()
