version: '3.8'

services:
  wagtail:
    ports:
      - 8000:8000
    environment:
      OV_API_URL: http://localhost:8000
  front:
    ports:
      - 3000:3000
    volumes:
      - ./ov-frontend:/var/app
    command: npm run dev
