site_name: 'Open Vault: Deploy'
site_description: Open Vault redesign deployment documentation
site_url: http://localhost:8001
repo_url: https://github.com/WGBH-MLA/ov-deploy/



markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables

theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: dark)'
      primary: purple
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - content.code.annotate # Enable code annotations for a specific block
    - header.autohide # Hide header when scrolling
    - navigation.instant # Load requests with XHR without reloading page
    - navigation.sections # Top level sections rendered as group in sidebar
    - navigation.tabs # Top level sections rendered as navbar
    - navigation.tabs.sticky # Tabs visible on scroll
    - navigation.top # Back to top button
    - navigation.tracking # Adds url#anchor to address bar
    - navigation.expand # Expand all collapsed sections by default
    - toc.integrate # Nav bar is always rendered on the left
    - search.highlight # Highlight occurances in result when searching for a term
    - search.suggest # Suggest results in search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WGBH-MLA/ov-deploy/
    - icon: fontawesome/regular/newspaper
      link: http://ovfrontend.k8s.wgbhdigital.org/
