#!/bin/bash
HELP="Open Vault init script\n\n

USAGE:\n\n

  ./ov COMMAND [args] \n\n

COMMANDS:\n\n

\t  b | build \t  build the docker images
\t  c | cmd \t    run a compose command \n
\t  d | dev \t    start a development server \n
\t  i | init \t   run initialization script \n
\t  h | help \t   prints this help text \n
\t  m | manage \t run a wagtail manage.py command \n
\t  s | shell \t  run a django shell command with the app context
"

OV_UID=$(id -u)
OV_GID=$(id -g)

COMPOSE_DEV="docker compose -f docker-compose.yml -f dev.yml"
MANAGE="run wagtail python3 manage.py"

if [ -z $1 ]; then
  echo -e $HELP

elif [ $1 = "build" -o $1 = "b" ]; then
  shift
  $COMPOSE_DEV build "$@"

elif [ $1 = "cmd" -o $1 = "c" ]; then
  shift
  # docker run -it -v $(pwd)/:/app/ ov "$@"
  $COMPOSE_DEV "$@"

elif [ $1 = "dev" -o $1 = "d" ]; then
  shift
  # docker run -itp 8000:8000 -v $(pwd)/:/app/ ov "$@"
  $COMPOSE_DEV up

elif [ $1 = "init" -o $1 = "i" ]; then
  shift
  # initialize submodule
  git submodule init
  # checkout current version
  git submodule update
  # build docker files
  ./ov build
  # Insatll npm requirements
  ./ov c run -it front npm install

elif [ $1 = "manage" -o $1 = "m" ]; then
  shift
  # docker run -it -v $(pwd)/:/app/ ov python3 manage.py "$@"
  $COMPOSE_DEV $MANAGE "$@"

elif [ $1 = "shell" -o $1 = "s" ]; then
  shift
  # docker run -it -v $(pwd)/:/app/ ov python3 manage.py shell "$@"
  $COMPOSE_DEV $MANAGE shell "$@"
elif [ $1 = "dump" -o $1 = "backup" ]; then
  shift
  TIMESTAMP=`date +%Y-%m-%d_%H-%M-%S`
  $COMPOSE_DEV exec -it db pg_dump -Fc -U postgres postgres > db_$TIMESTAMP.sql

elif [ $1 = "load" -o $1 = "restore" ]; then
  shift
  # Restore a database from a dump file $1
  $COMPOSE_DEV exec -iT db pg_restore --verbose --clean --no-acl --no-owner -U postgres -d postgres < $1

else echo -e $HELP

fi
