#!/bin/bash
HELP="Open Vault init script\n\n

USAGE:\n\n

  ./ov COMMAND [args] \n\n

COMMANDS:\n\n

\t  b | build \t  build the docker images
\t  c | cmd \t    run a compose command \n
\t  d | dev \t    start a development server \n
\t  h | help \t   prints this help text \n
\t  m | manage \t run a wagtail manage.py command \n
\t  s | shell \t  run a django shell command with the app context
"

OV_UID=$(id -u)
OV_GID=$(id -g)

COMPOSE_DEV="docker compose -f docker-compose.yml -f dev.yml"
MANAGE="run wagtail python3 manage.py"

if [ -z $1 ]; then
  echo -e $HELP

elif [ $1 = "build" -o $1 = "b" ]; then
  shift
  $COMPOSE_DEV build "$@"

elif [ $1 = "cmd" -o $1 = "c" ]; then
  shift
  # docker run -it -v $(pwd)/:/app/ ov "$@"
  $COMPOSE_DEV "$@"

elif [ $1 = "dev" -o $1 = "d" ]; then
  shift
  # docker run -itp 8000:8000 -v $(pwd)/:/app/ ov "$@"
  $COMPOSE_DEV up

elif [ $1 = "manage" -o $1 = "m" ]; then
  shift
  # docker run -it -v $(pwd)/:/app/ ov python3 manage.py "$@"
  $COMPOSE_DEV $MANAGE "$@"

elif [ $1 = "shell" -o $1 = "s" ]; then
  shift
  # docker run -it -v $(pwd)/:/app/ ov python3 manage.py shell "$@"
  $COMPOSE_DEV $MANAGE shell "$@"

else echo -e $HELP

fi
