apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ov-dev
  namespace: argo-cd
spec:
  project: ov
  source:
    repoURL: https://github.com/WGBH-MLA/ov-deploy
    path: charts/openvault
    targetRevision: alpine
    helm:
      valuesObject:
        organ:
          url: https://organ.wgbh-mla.org
  destination:
    server: https://kubernetes.default.svc
    namespace: ov
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
