apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ov-stage
  namespace: argo-cd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: wgbh-mla
        repo: ov-wag
      values:
        repo: ov-wag
  - pullRequest:
      github:
        owner: wgbh-mla
        repo: ov-frontend
      values:
        repo: ov-frontend
  template:
    metadata:
      name: '{{ .values.repo }}-pr-{{ .number }}'
    spec:
      project: ov
      source:
        repoURL: https://github.com/WGBH-MLA/ov-deploy
        path: charts/openvault
        helm:
          valuesObject:
            global:
              certIssuer: letsencrypt-production
              backend:
                image:
                  tag: '{{ if eq .values.repo "ov-wag" }}pr-{{ .number }}{{ else }}main{{ end }}'
              frontend:
                image:
                  tag: '{{ if eq .values.repo "ov-frontend" }}pr-{{ .number }}{{ else }}main{{ end }}'
            app-template:
              serviceAccount:
                db: {}
              controllers:
                # initialize the database if it does not exist
                init-db:
                  type: job
                  annotations:
                    argocd.argoproj.io/hook: Sync
                  serviceAccount:
                    identifier: db
                  containers:
                    init-db:
                      image:
                        repository: alpine/psql
                        tag: 17.6
                      envFrom:
                      - configMapRef:
                          name: '{{ .values.repo }}-pr-{{ .number }}-backend'
                      - secretRef:
                          name: '{{ .values.repo }}-pr-{{ .number }}-backend-secret'
                      env:
                      - name: SOURCE_DB_NAME
                        value: ov-dev
                      command:
                      - /bin/sh
                      - -c
                      - |
                        DB_URL="postgresql://$OV_DB_USER:$OV_DB_PASSWORD@$OV_DB_HOST:$OV_DB_PORT"
                        export "PGPASSWORD=$OV_DB_PASSWORD"

                        MAX_RETRIES=5
                        # Check if the database is ready
                        until pg_isready -h "$OV_DB_HOST" -p "$OV_DB_PORT" -U "$OV_DB_USER"; do
                          if [ $((MAX_RETRIES--)) -eq 0 ]; then
                            >&2 echo "Error: PostgreSQL is not ready after multiple attempts. Exiting..."
                            exit 1
                          fi
                          echo "Waiting for PostgreSQL to be ready..."
                          sleep 5
                        done

                        # Check if the database exists by attempting to connect
                        MESSAGE=$(psql "$DB_URL/$OV_DB_NAME" -c '\q' 2>&1 > /dev/null)

                        if [ $? -ne 0 ]; then
                          echo "Error: Failed to connect to the database. Message: $MESSAGE"
                          exit 1
                        fi

                        # Check if the database is already initialized by looking for a page
                        PAGE_CHECK=$(psql "$DB_URL/$OV_DB_NAME" -t -c "SELECT EXISTS(SELECT 1 FROM wagtailcore_page);")

                        if [[ "$PAGE_CHECK" =~ "t" ]]; then
                          echo "Database $OV_DB_NAME is already initialized."
                          exit 0
                        fi

                        echo "Attempting to dump | restore into the new database..." &&\
                        pg_dump "$DB_URL/$SOURCE_DB_NAME" | psql "$DB_URL/$OV_DB_NAME" &&\
                        echo "Database $OV_DB_NAME created and restored successfully!" &&\
                        exit 0 || {
                          >&2 echo "Failed to create or restore the database."
                          exit 1
                        }

            organ:
              url: https://organ.wgbh-mla.org
      destination:
        server: https://kubernetes.default.svc
        namespace: ov
      syncPolicy:
        automated:
          prune: true
          # selfHeal: true
