apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ov-wag-tls
spec:
  secretName: ov-wag-tls
  dnsNames:
    - admin.ov.wgbh-mla.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
