apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: {{ .Values.frontend.name }}
  name: {{ .Values.frontend.name }}

spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}

    spec:
      containers:
        - image: ghcr.io/wgbh-mla/ov-frontend:main
          imagePullPolicy: Always
          name: {{ .Values.frontend.name }}
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 50Mi
          envFrom:
            - configMapRef:
                name: {{ .Values.frontend.name }}-config
            - secretRef:
                name: {{ .Values.frontend.name }}-secret
          ports:
            - containerPort: 3000
              name: http
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 20
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 3
            periodSeconds: 30
