apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openvault.frontend.fullname" . }}-config
data:
  NODE_ENV: production
  OV_API_URL: 'http://{{ template "openvault.backend.fullname" . }}'
  # AAPB_HOST: https://americanarchive.org
  AAPB_HOST: https://demo.aapb.wgbh-mla.org
  ORGAN_URL: http://organ.organ
  ES_URL: http://quickstart-es-http.es-demo:9200
