apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openvault.frontend.fullname" . }}-secret
  labels:
{{ include "bjw-s.common.lib.metadata.allLabels" . | indent 4 }}
stringData:
  ES_API_KEY: {{ .Values.global.frontend.elasticApiKey | quote }}
  ES_INDEX: {{ .Values.global.frontend.elasticIndex | quote }}
