apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openvault.frontend.fullname" . }}-secret
  labels:
{{ include "bjw-s.common.lib.metadata.allLabels" . | indent 4 }}
stringData:
  ES_API_KEY: {{ .Values.elasticsearch.apiKey | default "" | quote }}
  {{ if .Values.cookies.id -}}
  COOKIE_CONSENT_ID: {{ .Values.cookies.id | quote }}
  {{ end }}
