apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.17.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
      http.cors.allow-origin: /(^https:\/\/openvault.wgbh.org)|(^https:\/\/admin.ov.wgbh-mla.org)|(^https:\/\/elastic.wgbh-mla.org)|(^https?:\/\/localhost(:[0-9]+)?)/
      http.cors.enabled: true
      http.cors.allow-credentials: true
      http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
      http.cors.allow-headers: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept, x-elastic-client-meta
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
        storageClassName: efs-sc
  http:
    tls:
      selfSignedCertificate:
        disabled: true
      certificate:
        secretName: elastic-certs
