apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.17.2
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    server.publicBaseUrl: https://search.wgbh-mla.org
  http:
    tls:
      selfSignedCertificate:
        disabled: true
      certificate:
        secretName: kibana-certs
