apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ov-frontend-tls
spec:
  secretName: ov-frontend-tls
  dnsNames:
    - openvault.wgbh.org
  issuerRef:
    name: letsencrypt-production-http
    kind: ClusterIssuer
