apiVersion: v1
kind: ConfigMap
metadata:
  name: ov-frontend-config
data:
  NODE_ENV: production
  OV_API_URL: http://ov-wag
  AAPB_HOST: https://americanarchive.org
  ORGAN_URL: http://organ.organ
  ES_URL: https://elastic.wgbh-mla.org