apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ov-frontend-ingress

spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ov.wgbh-mla.org`)
      services:
        - kind: Service
          name: ov-frontend
          port: 80
      middlewares:
        - name: public-ratelimit
