apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-{{ .Values.backend.name }}-config"
data:
  DJANGO_SETTINGS_MODULE: ov_wag.settings.production
  OV_ALLOWED_HOSTS: '*'
  OV_TRUSTED_ORIGINS: https://admin.ov.wgbh-mla.org,http://localhost:8000
  OV_DEBUG: 'false'
  OV_CSRF_COOKIE_SECURE: 'false'
  OV_API_URL: http://ov-wag/api/v2
  OV_BASE_URL: https://openvault.wgbh.org
  OV_ADMIN_BASE_URL: https://admin.ov.wgbh-mla.org
  OV_HOST: '0.0.0.0:8000'
  OV_WORKERS: '1'
  OV_FORWARDED_ALLOW_IPS: '*'
  OV_ACCESS_LOGFILE: '-'
  OV_ERROR_LOGFILE: '-'
  OV_PREVIEW_URL: https://openvault.wgbh.org/preview
  AWS_STORAGE_BUCKET_NAME: media.openvault.wgbh.org
