apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          resources:
            limits:
              cpu: '2'
              memory: '2Gi'
            requests:
              cpu: '100m'
              memory: '100Mi'
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-efs-claim
