kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-efs-claim # Sets name of PVC
  labels:
    app: postgres
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany # Sets read and write access
  resources:
    requests:
      storage: 1Gi # Sets volume size
