kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-ov-efs-claim
  labels:
    app: postgres
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
